In [1]:
"""
More on rpy2 options
https://ipython.org/ipython-doc/2/config/extensions/rmagic.html
"""
import rpy2
%load_ext rpy2.ipython

C:\Users\Joseph\anaconda3\lib\site-packages\rpy2\robjects\packages.py:365: UserWarning: The symbol 'quartz' is not in this R namespace/package.
  warnings.warn(


# 1. DEVORESTAT9 5.E.001.MI.
<p>
 A service station has both self-service and full-service islands. On each island, there is a single regular unleaded pump with two hoses. Let X denote the number of hoses being used on the self-service island at a particular time, and let Y denote the number of hoses on the full-service island in use at that time. The joint pmf of X and Y appears in the accompanying tabulation.
</p>
<img src="images/5_1_and_5_2_problem_1.png" alt="5_1_and_5_2_problem_1.png" style="float:left;">

In [2]:
# It's not really worth copying the text because it's in a weird format.
# I Suggest removing the x and y part then formatting.
p1_string = """
p(x, y)
0	1	2
0	0.10	0.03	0.01
1	0.06	0.20	0.07
2	0.06	0.14	0.33
"""

p1_data = p1_string.split("\n")  # Split by new line
p1_data = [i for i in p1_data if i]  # Remove empty
# remove the first item in the list because it's not useful
p1_data = p1_data[1:]

p1_data = [i.split("\t") for i in p1_data]
p1_data_header = p1_data[0]  # Get the headers
p1_data = p1_data[1:]  # Drop the headers from p1_data
# Ignore the first data point in the inner list
p1_data = [i[1:] for i in p1_data]
print(p1_data)

[['0.10', '0.03', '0.01'], ['0.06', '0.20', '0.07'], ['0.06', '0.14', '0.33']]


In [3]:
import numpy as np
import pandas as pd

p1_np_array = np.array(p1_data)
p1_np_array = p1_np_array.astype(np.float64)  # Set type to float
print(p1_np_array.dtype)
print(p1_np_array)

float64
[[0.1  0.03 0.01]
 [0.06 0.2  0.07]
 [0.06 0.14 0.33]]


### (a) What is P(X = 1 and Y = 1)?

In [4]:
p1a_solution = p1_np_array[1][1]  # [row][column]
print(p1a_solution)
print()

p1a_solution = p1_np_array[1,1]  # [row, column]
print(p1a_solution)

0.2

0.2


### (b) Compute P(X ≤ 1 and Y ≤ 1).

In [5]:
p1b_np_array = p1_np_array[:2, :2]
print(p1b_np_array)
print()

p1b_solution = np.sum(p1b_np_array)
print(f"{p1b_solution=}")

[[0.1  0.03]
 [0.06 0.2 ]]

p1b_solution=0.39


### (c) Give a word description of the event {X ≠ 0 and Y ≠ 0}.
<img src="images/5_1_and_5_2_problem_1c_solution.png" alt="5_1_and_5_2_problem_1c_solution.png" style="float:left;">

#### Compute the probability of this event.


In [6]:
print("Matrix of p1_np_array")
print(p1_np_array)
print()

p1c_np_array = p1_np_array[1:, 1:]
print("Submatrix of p1_np_array from [1:, 1:]")
print(p1c_np_array)
print()

p1c_solution = np.sum(p1c_np_array)
print("Sum of submatrix")
print(p1c_solution)

Matrix of p1_np_array
[[0.1  0.03 0.01]
 [0.06 0.2  0.07]
 [0.06 0.14 0.33]]

Submatrix of p1_np_array from [1:, 1:]
[[0.2  0.07]
 [0.14 0.33]]

Sum of submatrix
0.74


### (d) Compute the marginal pmf of X.


In [7]:
# X is the rows
p1d_column_sum = np.sum(p1_np_array, axis=1)
print("X is the row (You need to add the columns to get the sum of a row)")
print("Column sum (Marginal PMF of X)")
print(np.vstack(p1d_column_sum))
print()

X is the row (You need to add the columns to get the sum of a row)
Column sum (Marginal PMF of X)
[[0.14]
 [0.33]
 [0.53]]



### (d) Compute the marginal pmf of Y.


In [8]:
# Y is the columns
p1d_row_sum = np.sum(p1_np_array, axis=0)
print("Y is the column (You need to add the rows to get the sum of a column)")
print("Row sum (Marginal PMF of Y)")
print(p1d_row_sum)

Y is the column (You need to add the rows to get the sum of a column)
Row sum (Marginal PMF of Y)
[0.22 0.37 0.41]


<img src="images/5_1_and_5_2_problem_1d_solution.png" alt="5_1_and_5_2_problem_1d_solution.png" style="float:left;">

#### Using P_X(x), what is P(X ≤ 1)?

In [9]:
# It's of the P sub X, which is the marginal PMF of X

p1d_marignal_PMF_of_X_less_than_equal_to_1 = p1d_column_sum[:2]
print("Marginal PMF of X <= 1")
print(p1d_marignal_PMF_of_X_less_than_equal_to_1)
print()

p1d_solution = np.sum(p1d_marignal_PMF_of_X_less_than_equal_to_1)
print("Sum of the Marginal PMF of X <= 1")
print(p1d_solution)

Marginal PMF of X <= 1
[0.14 0.33]

Sum of the Marginal PMF of X <= 1
0.47000000000000003


### (e) Are X and Y independent rv's? Explain.
<img src="images/5_1_and_5_2_problem_1e_solution.png" alt="5_1_and_5_2_problem_1e_solution.png" style="float:left;">

# 2. DEVORESTAT9 5.E.018.
<p>
A service station has both self-service and full-service islands. On each island, there is a single regular unleaded pump with two hoses. Let X denote the number of hoses being used on the self-service island at a particular time, and let Y denote the number of hoses on the full-service island in use at that time. The joint pmf of X and Y appears in the accompanying tabulation. </p>

<img src="images/5_1_and_5_2_problem_2.png" alt="5_1_and_5_2_problem_2.png" style="float:left;">

In [10]:
# It's not really worth copying the text because it's in a weird format.
# I Suggest removing the x and y part then formatting.
p2_string = """
p(x, y)
    		0	1	2
0  	  0.10  	  0.05  	  0.02  
1  	  0.06  	  0.20  	  0.08  
2  	  0.06  	  0.14  	  0.29 
"""

p2_data = p2_string.split("\n")  # Split by new line
p2_data = [i for i in p2_data if i]  # Remove empty
# remove the first item in the list because it's not useful
p2_data = p2_data[1:]

p2_data = [i.split("\t") for i in p2_data]
p2_data_header = p2_data[0]  # Get the headers
p2_data = p2_data[1:]  # Drop the headers from p1_data
# Ignore the first data point in the inner list
p2_data = [i[1:] for i in p2_data]
print(p2_data)

[['  0.10  ', '  0.05  ', '  0.02  '], ['  0.06  ', '  0.20  ', '  0.08  '], ['  0.06  ', '  0.14  ', '  0.29 ']]


In [11]:
p2_np_array = np.array(p2_data)
p2_np_array = p2_np_array.astype(np.float64)  # Set type to float
print(p2_np_array.dtype)
print(p2_np_array)

float64
[[0.1  0.05 0.02]
 [0.06 0.2  0.08]
 [0.06 0.14 0.29]]


### (a) Given that X = 1, determine the conditional pmf of Y—i.e., pY|X(0|1), pY|X(1|1), pY|X(2|1). (Round your answers to four decimal places.)
<img src="images/5_1_and_5_2_problem_2a_wording.png" alt="5_1_and_5_2_problem_2a_wording.png" style="float:left;">

In [12]:
# X is the rows
print("X is the row (You need to add the columns to get the sum of a row)")
p2a_column_sum = np.sum(p2_np_array, axis=1)
print("Column sum (Marginal PMF of X)")
print(np.vstack(p2a_column_sum))
print()

# Y is the columns
print("Y is the column (You need to add the rows to get sum of a column)")
p2a_row_sum = np.sum(p2_np_array, axis=0)
print("Row sum (Marginal PMF of Y)")
print(p2a_row_sum)

X is the row (You need to add the columns to get the sum of a row)
Column sum (Marginal PMF of X)
[[0.17]
 [0.34]
 [0.49]]

Y is the column (You need to add the rows to get sum of a column)
Row sum (Marginal PMF of Y)
[0.22 0.39 0.39]


In [13]:
print("Column sum (Marginal PMF of X) (Just look at row index 1)")
print(np.vstack(p2a_column_sum))
print()

# Given X = 1 (x Row 1)
p2a_row_index_1 = p2_np_array[1]
p2a_X_marginal_at_row_index_1 = p2a_column_sum[1]

print("X Row at index 1")
print(p2a_row_index_1)
print()

print("Marginal sum of X Row at index 1")
print(p2a_X_marginal_at_row_index_1)
print()

p2a_solution = p2a_row_index_1 / p2a_X_marginal_at_row_index_1

print("(X Row at index 1) / (Marginal sum of X Row at index 1)")
print(p2a_solution)

Column sum (Marginal PMF of X) (Just look at row index 1)
[[0.17]
 [0.34]
 [0.49]]

X Row at index 1
[0.06 0.2  0.08]

Marginal sum of X Row at index 1
0.34

(X Row at index 1) / (Marginal sum of X Row at index 1)
[0.17647059 0.58823529 0.23529412]


<img src="images/5_1_and_5_2_problem_2a_solution.png" alt="5_1_and_5_2_problem_2a_solution.png" style="float:left;">

### (b) Given that two hoses are in use at the self-service island, what is the conditional pmf of the number of hoses in use on the full-service island? (Round your answers to four decimal places.)


In [14]:
print("Column sum (Marginal PMF of X) (Just look at row index 2)")
print(np.vstack(p2a_column_sum))
print()

# Given 2 hoses (x Row 2 )
p2b_row_index_2 = p2_np_array[2]
p2b_X_marginal_at_row_index_2 = p2a_column_sum[2]

print("X Row at index 2")
print(p2b_row_index_2)
print()

print("Marginal sum of X Row at index 2")
print(p2b_X_marginal_at_row_index_2)
print()

p2a_solution = p2b_row_index_2 / p2b_X_marginal_at_row_index_2

print("(X Row at index 2) / (Marginal sum of X Row at index 2)")
print(p2a_solution)

Column sum (Marginal PMF of X) (Just look at row index 2)
[[0.17]
 [0.34]
 [0.49]]

X Row at index 2
[0.06 0.14 0.29]

Marginal sum of X Row at index 2
0.49

(X Row at index 2) / (Marginal sum of X Row at index 2)
[0.12244898 0.28571429 0.59183673]


<img src="images/5_1_and_5_2_problem_2b_solution.png" alt="5_1_and_5_2_problem_2b_solution.png" style="float:left;">

### (c) Use the result of part (b) to calculate the conditional probability P(Y ≤ 1 | X = 2). (Round your answer to four decimal places.)


In [15]:
p2c_row = p2a_solution
print("row = Solution to part b")
print(p2c_row)
print()

p2c_row = p2c_row[:2]
print("Values of row based on Y <= 1")
print(p2c_row)
print()


p2c_solution = np.sum(p2c_row)

print("Sum from 0 to 1 of row")
print(p2c_solution)

row = Solution to part b
[0.12244898 0.28571429 0.59183673]

Values of row based on Y <= 1
[0.12244898 0.28571429]

Sum from 0 to 1 of row
0.40816326530612246


### (d) Given that two hoses are in use at the full-service island, what is the conditional pmf of the number in use at the self-service island? (Round your answers to four decimal places.)


In [16]:
p2d_column_index_2 = p2_np_array[:, 2]  # TODO FIX MY NAME
p2d_Y_marginal_at_column_index_2 = p2a_row_sum[2]

print("Y Column at index 2")
print(np.vstack(p2d_column_index_2))
print()

print("Marginal sum of Y Column at index 2")
print(p2d_Y_marginal_at_column_index_2)
print()

p2d_solution = p2d_column_index_2 / p2d_Y_marginal_at_column_index_2

print("(Y Column at index 2) / (Marginal sum of Y Column at index 2)")
print(np.vstack(p2d_solution))

Y Column at index 2
[[0.02]
 [0.08]
 [0.29]]

Marginal sum of Y Column at index 2
0.39

(Y Column at index 2) / (Marginal sum of Y Column at index 2)
[[0.05128205]
 [0.20512821]
 [0.74358974]]


<img src="images/5_1_and_5_2_problem_2d_solution.png" alt="5_1_and_5_2_problem_2d_solution.png" style="float:left;">

# 3. DEVORESTAT9 5.E.003.
<p>
A certain market has both an express checkout line and a superexpress checkout line. Let X1 denote the number of customers in line at the express checkout at a particular time of day, and let X2 denote the number of customers in line at the superexpress checkout at the same time. Suppose the joint pmf of X1 and X2 is as given in the accompanying table.
</p>
<img src="images/5_1_and_5_2_problem_3.png" alt="5_1_and_5_2_problem_3.png" style="float:left;">

In [17]:
# It's not really worth copying the text because it's in a weird format.
# I Suggest removing the x1 and x2 part then formatting.
p3_string = """

0	1	2	3
0  	  0.09  	  0.06  	  0.04  	  0.00  
1  	  0.05  	  0.15  	  0.05  	  0.04  
2  	  0.05  	  0.03  	  0.10  	  0.06  
3  	  0.01  	  0.04  	  0.04  	  0.07  
4  	  0.00  	  0.02  	  0.05  	  0.05
"""

p3_data = p3_string.split("\n")  # Split by new line
p3_data = [i for i in p3_data if i]  # Remove empty
# remove the first item in the list because it's not useful
p2_data = p2_data[1:]

p3_data = [i.split("\t") for i in p3_data]
p3_data_header = p3_data[0]  # Get the headers
p3_data = p3_data[1:]  # Drop the headers from p1_data
# Ignore the first data point in the inner list
p3_data = [i[1:] for i in p3_data]
print(p3_data)

[['  0.09  ', '  0.06  ', '  0.04  ', '  0.00  '], ['  0.05  ', '  0.15  ', '  0.05  ', '  0.04  '], ['  0.05  ', '  0.03  ', '  0.10  ', '  0.06  '], ['  0.01  ', '  0.04  ', '  0.04  ', '  0.07  '], ['  0.00  ', '  0.02  ', '  0.05  ', '  0.05']]


In [18]:
p3_np_array = np.array(p3_data)
p3_np_array = p3_np_array.astype(np.float64)  # Set type to float
print(p3_np_array.dtype)
print(p3_np_array)

float64
[[0.09 0.06 0.04 0.  ]
 [0.05 0.15 0.05 0.04]
 [0.05 0.03 0.1  0.06]
 [0.01 0.04 0.04 0.07]
 [0.   0.02 0.05 0.05]]


### (a) What is P(X1 = 1, X2 = 1), that is, the probability that there is exactly one customer in each line?
P(X1 = 1, X2 = 1) =

In [19]:
p3a_solution = p3_np_array[1, 1]
print(p3a_solution)

0.15


### (b) What is P(X1 = X2), that is, the probability that the numbers of customers in the two lines are identical?
P(X1 = X2) =

In [20]:
"""
Reference:
    numpy.diag
        https://numpy.org/doc/stable/reference/generated/numpy.diag.html
"""

# X1 = X2 ONLY ON THE DIAGONAL
p3b_np_array_diagonal = p3_np_array.diagonal()
print("The Diagonal (Where X = Y)")
print(p3b_np_array_diagonal)
print()

print("Diagonal Matrix")
print(np.diag(p3b_np_array_diagonal))
print()

p3b_solution = np.sum(p3b_np_array_diagonal)
print("The sum of the diagonal of p3_np_array")
print(p3b_solution)


The Diagonal (Where X = Y)
[0.09 0.15 0.1  0.07]

Diagonal Matrix
[[0.09 0.   0.   0.  ]
 [0.   0.15 0.   0.  ]
 [0.   0.   0.1  0.  ]
 [0.   0.   0.   0.07]]

The sum of the diagonal of p3_np_array
0.41


### (c) Let A denote the event that there are at least two more customers in one line than in the other line. Express A in terms of X1 and X2.
<p>
Either X1 >= 2 + X2 or X2 >= 2 + X1
</p>
<img src="images/5_1_and_5_2_problem_3c_solution.png" alt="5_1_and_5_2_problem_3c_solution.png" style="float:left;">


#### Calculate the probability of this event.
P(A) =

In [21]:
"""
Reference:
    Replace sub part of matrix by another small matrix in numpy
        https://stackoverflow.com/questions/26506204/replace-sub-part-of-matrix-by-another-small-matrix-in-numpy

"""
print("Original Array")
print(p3_np_array)
print("-"*100)
print()
###################################################################################################
# V1

print("Version 1")
p3c_np_array = p3_np_array.copy()


# Naive Ghetto loop
for i, v in enumerate(p3c_np_array):
    if i == 0:
        v[i:i+2] = 0
    else:
        v[i-1:i+2] = 0

print("Naive Ghetto loop for {X1 >= 2 + X2 OR X2 >= 2 + X1}")
print(p3c_np_array)
print()

p3c_solution = np.sum(p3c_np_array)
print("Sum of the array that meets the condition")
print(f"{p3c_solution:.2f}")

print("-"*100)
print()
###################################################################################################
# V2

print("Version 2")
p3c_np_array = p3_np_array.copy()

for row_index, row_value in enumerate(p3c_np_array):
    for col_index, col_value in enumerate(row_value):
        if row_index < col_index + 2 and col_index < row_index + 2:
            row_value[col_index] = 0


print("Naive Proper Loop for {X1 >= 2 + X2 OR X2 >= 2 + X1}")
print(p3c_np_array)
print()

p3c_solution = np.sum(p3c_np_array)
print("Sum of the array that meets the condition")
print(f"{p3c_solution:.2f}")

print("-"*100)
print()
###################################################################################################
"""
Rerference:
    numpy.ndindex
        https://numpy.org/doc/stable/reference/generated/numpy.ndindex.html
            Loop over the shape of the array
"""
# V3

print("Version 3")
p3c_np_array = p3_np_array.copy()

for row_index, col_index in np.ndindex(p3c_np_array.shape):
    if (row_index < col_index + 2) and (col_index < row_index + 2):
        p3c_np_array[row_index, col_index] = 0


print("Numpy Proper Loop for {X1 >= 2 + X2 OR X2 >= 2 + X1}")
print(p3c_np_array)
print()

p3c_solution = np.sum(p3c_np_array)
print("Sum of the array that meets the condition")
print(f"{p3c_solution:.2f}")

Original Array
[[0.09 0.06 0.04 0.  ]
 [0.05 0.15 0.05 0.04]
 [0.05 0.03 0.1  0.06]
 [0.01 0.04 0.04 0.07]
 [0.   0.02 0.05 0.05]]
----------------------------------------------------------------------------------------------------

Version 1
Naive Ghetto loop for {X1 >= 2 + X2 OR X2 >= 2 + X1}
[[0.   0.   0.04 0.  ]
 [0.   0.   0.   0.04]
 [0.05 0.   0.   0.  ]
 [0.01 0.04 0.   0.  ]
 [0.   0.02 0.05 0.  ]]

Sum of the array that meets the condition
0.25
----------------------------------------------------------------------------------------------------

Version 2
Naive Proper Loop for {X1 >= 2 + X2 OR X2 >= 2 + X1}
[[0.   0.   0.04 0.  ]
 [0.   0.   0.   0.04]
 [0.05 0.   0.   0.  ]
 [0.01 0.04 0.   0.  ]
 [0.   0.02 0.05 0.  ]]

Sum of the array that meets the condition
0.25
----------------------------------------------------------------------------------------------------

Version 3
Numpy Proper Loop for {X1 >= 2 + X2 OR X2 >= 2 + X1}
[[0.   0.   0.04 0.  ]
 [0.   0.   0.   0.04]



### (d) What is the probability that the total number of customers in the two lines is exactly four? At least four?

#### P(exactly four)	=

In [22]:
print("Original Array")
print(p3_np_array)
print("-"*100)
print()
###################################################################################################

p3d1_np_array = p3_np_array.copy()

for row_index, col_index in np.ndindex(p3d1_np_array.shape):
    
    # A lot easier to look for the inverse and set the value at the position to be 0
    if row_index + col_index !=4:
        p3d1_np_array[row_index, col_index] = 0
        
print("Numpy Proper Loop for P(exactly four)")
print(p3d1_np_array)
print()

p3d1_solution = np.sum(p3d1_np_array)
print("Sum of the array that meets the condition")
print(f"{p3d1_solution:.2f}")

Original Array
[[0.09 0.06 0.04 0.  ]
 [0.05 0.15 0.05 0.04]
 [0.05 0.03 0.1  0.06]
 [0.01 0.04 0.04 0.07]
 [0.   0.02 0.05 0.05]]
----------------------------------------------------------------------------------------------------

Numpy Proper Loop for P(exactly four)
[[0.   0.   0.   0.  ]
 [0.   0.   0.   0.04]
 [0.   0.   0.1  0.  ]
 [0.   0.04 0.   0.  ]
 [0.   0.   0.   0.  ]]

Sum of the array that meets the condition
0.18


#### P(at least four)	=

In [23]:
print("Original Array")
print(p3_np_array)
print("-"*100)
print()
###################################################################################################

p3d2_np_array = p3_np_array.copy()

for row_index, col_index in np.ndindex(p3d2_np_array.shape):
    
    # A lot easier to look for the inverse and set the value at the position to be 0
    # Inverse of at least 4 (x >= 4) is less than 4 (x < 4) 
    if row_index + col_index < 4:
        p3d2_np_array[row_index, col_index] = 0
        
print("Numpy Proper Loop for P(at least four)")
print(p3d2_np_array)
print()

p3d2_solution = np.sum(p3d2_np_array)
print("Sum of the array that meets the condition")
print(f"{p3d2_solution:.2f}")

Original Array
[[0.09 0.06 0.04 0.  ]
 [0.05 0.15 0.05 0.04]
 [0.05 0.03 0.1  0.06]
 [0.01 0.04 0.04 0.07]
 [0.   0.02 0.05 0.05]]
----------------------------------------------------------------------------------------------------

Numpy Proper Loop for P(at least four)
[[0.   0.   0.   0.  ]
 [0.   0.   0.   0.04]
 [0.   0.   0.1  0.06]
 [0.   0.04 0.04 0.07]
 [0.   0.02 0.05 0.05]]

Sum of the array that meets the condition
0.47


# 4. DEVORESTAT9 5.E.006.S.
<img src="images/5_1_and_5_2_problem_4.png" alt="5_1_and_5_2_problem_4.png" style="float:left;">
<p style="float:left">
 Sixty-five percent of all customers who purchase these cameras also buy an extended warranty. Let Y denote the number of purchasers during this week who buy an extended warranty.
</p>

In [24]:
p4_string = """
x	0	1	2	3	4
pX(x)    	  0.1  	  0.2  	  0.3  	  0.25 	  0.15  

"""

p4_data = p4_string.split("\n")
p4_data = [i for i in p4_data if i]
p4_data = [i.split("\t") for i in p4_data]
p4_data_headers = [i[0] for i in p4_data]
p4_data = [i[1:] for i in p4_data]

print(p4_data_headers)
print(p4_data)
print()

p4_percent_all_customers_who_purchase_cameras_also_buy_extended_warranty = .65
print(f"Percent all customers who purchace Cameras also buy extended warranty:\n{p4_percent_all_customers_who_purchase_cameras_also_buy_extended_warranty}")

['x', 'pX(x)    ']
[['0', '1', '2', '3', '4'], ['  0.1  ', '  0.2  ', '  0.3  ', '  0.25 ', '  0.15  ']]

Percent all customers who purchace Cameras also buy extended warranty:
0.65


In [25]:
p4_np_array = np.array(p4_data)
p4_np_array = p4_np_array.astype(np.float64)
print(p4_np_array)

[[0.   1.   2.   3.   4.  ]
 [0.1  0.2  0.3  0.25 0.15]]


### (a) What is P(X = 4, Y = 2)? 

### [Hint: This probability equals P(Y = 2|X = 4) · P(X = 4); now think of the four purchases as four trials of a binomial experiment, with success on a trial corresponding to buying an extended warranty.] (Round your answer to four decimal places.)


In [26]:
p4a_X = 4
print(f"X=4 -> {p4a_X}")
print()

p4a_Y = 2
print(f"Y=2 -> {p4a_Y}")
print()

p4a_P_of_X = p4_np_array[1,4]
print(f"P(X=4) -> {p4a_P_of_X}")
print()

X=4 -> 4

Y=2 -> 2

P(X=4) -> 0.15



#### P(X = 4, Y = 2) =

In [27]:
import math
from scipy.stats import binom


def dbinom(k, n, p):
    """
    Simple dbinom equivalent in python

    """
    solution = math.comb(n, k) * (p)**(k) * (1 - p)**(n-k)
    return solution


print("Custom function method")
# binom.pmf(k, n, p) == binom.pmf(discrete number (trial), number of trials, probability of each trial). Note: k <= n
p4a_solution_v1 = dbinom(2, 4, .65) * .15
print(p4a_solution_v1)
print()

print("Scipy method")
# binom.pmf(k, n, p) == binom.pmf(discrete number (trial), number of trials, probability of each trial). Note: k <= n
p4a_solution_v2 = binom.pmf(2, 4, .65) * .15
print(p4a_solution_v2)
print()

print("Scipy method using the variables defined")
# binom.pmf(k, n, p) == binom.pmf(discrete number (trial), number of trials, probability of each trial). Note: k <= n
p4a_solution_v3 = binom.pmf(p4a_Y, p4a_X, p4_percent_all_customers_who_purchase_cameras_also_buy_extended_warranty) * p4a_P_of_X
print(p4a_solution_v2)


Custom function method
0.046580624999999994

Scipy method
0.046580624999999994

Scipy method using the variables defined
0.046580624999999994


In [28]:
%%R 

cat("R solution\n")
# dbinom(k, n, p) == binom.pmf(discrete number (trial), number of trials, probability of each trial). Note: k <= n
print(dbinom(2, 4, .65) * .15)


R solution
[1] 0.04658062


## Creating the Table for visual reference and for part b


In [29]:
from typing import Tuple


def np_arary_to_dict(np_array: np.array):

    np_array_transposed = np_array.transpose()

    dict_temp = {}

    for row in np_array_transposed:
        dict_temp[row[0]] = row[1]

    return dict_temp


def create_joint_distribution_as_pd_df_and_np_array(dict_np_array: dict, probability_of_winning: float) -> Tuple[pd.DataFrame, np.array]:

    number_of_rows = len(dict_np_array)

    list_list_row_current = []

    for row_index in range(number_of_rows):
        list_row_current = []

        for column_value in dict_np_array:
            """
            binom.pmf(k, n, p) == binom.pmf(discrete number (trial), number of trials, probability of each trial). 
            Note: k <= n

            So:
                binom.pmf(X, Y, probability_of_winning) * Probabilty at X
                OR
                binom.pmf(Y, X, probability_of_winning) * Probabilty at Y
            """
            value_at_cell = binom.pmf(
                row_index, column_value, probability_of_winning) * dict_np_array[column_value]

            list_row_current.append(value_at_cell)

        list_list_row_current.append(list_row_current)

    pd_df_temp = pd.DataFrame(list_list_row_current,
                              columns=dict_np_array.keys())

    np_array_temp = np.array(list_list_row_current)

    return pd_df_temp, np_array_temp

In [30]:
from IPython.display import display, HTML

# Recall
print("This is the given np array")
print(p4_np_array)
print()

# You need a dict of this array for probabiliy access
print("This the dict of the np array")
p4a_dict = np_arary_to_dict(p4_np_array)
for key, value in p4a_dict.items():
    print(key, value)
print()

# Creating the table then display it
print("Displaying the Joint Distirbution Table")

p4a_tables = create_joint_distribution_as_pd_df_and_np_array(p4a_dict, .65)
display(p4a_tables[0])

This is the given np array
[[0.   1.   2.   3.   4.  ]
 [0.1  0.2  0.3  0.25 0.15]]

This the dict of the np array
0.0 0.1
1.0 0.2
2.0 0.3
3.0 0.25
4.0 0.15

Displaying the Joint Distirbution Table


0.0   1.0      2.0       3.0       4.0
0  0.1  0.07  0.03675  0.010719  0.002251
1  0.0  0.13  0.13650  0.059719  0.016721
2  0.0  0.00  0.12675  0.110906  0.046581
3  0.0  0.00  0.00000  0.068656  0.057671
4  0.0  0.00  0.00000  0.000000  0.026776

### (b) Calculate P(X = Y). (Round your answer to four decimal places.)
P(X = Y) =

In [31]:
# The pandas DF of the joint distribution table
p4b_pd_df = p4a_tables[0]

# Generator to find when column name = row index (which is a name)
def generator_pd_df_column_name_eq_row_index(pd_df_given: pd.DataFrame):
    for row_index, row in pd_df_given.iterrows():
        for column_name in pd_df_given.columns:
            if row_index == column_name:

                # Need loc not iloc because we are using row/column names not row/column indexies
                yield pd_df_given.loc[row_index, column_name]


p4b_np_array_X_eq_Y = np.fromiter(
    generator_pd_df_column_name_eq_row_index(p4b_pd_df), dtype="float")


p4b_np_array_X_eq_Y_sum = np.sum(p4b_np_array_X_eq_Y)
print("Sum of the the joint distribution table where P(X = Y)")
print(p4b_np_array_X_eq_Y_sum)

Sum of the the joint distribution table where P(X = Y)
0.4521821875


### (c) Determine the joint pmf of X and Y.
<img src="images/5_1_and_5_2_problem_4c_1_solution.png" alt="5_1_and_5_2_problem_4c_1_solution.png" style="float:left;">

#### Determine the marginal pmf of Y. (Round your answers to four decimal places.)
<img src="images/5_1_and_5_2_problem_4c_2_solution.png" alt="5_1_and_5_2_problem_4c_2_solution.png" style="float:left;">

# 5. DEVORESTAT9 5.E.022.MI.
An instructor has given a short quiz consisting of two parts. For a randomly selected student, let X = the number of points earned on the first part and Y = the number of points earned on the second part. Suppose that the joint pmf of X and Y is given in the accompanying table.
<img src="images/5_1_and_5_2_problem_5.png" alt="5_1_and_5_2_problem_5.png" style="float:left;">

In [89]:
p5_data = """
0.01	0.06	0.02	0.10
0.04	0.13	0.20	0.10
0.01	0.15	0.17	0.01

"""

# Manually write the column and index names
p5_COLUMN_NAMES = [0, 5, 10, 15]
p5_INDEX_NAMES = [0, 5, 10]

print("Column names")
print(p5_COLUMN_NAMES)
print()

print("Index names")
# print(np.array(p5_INDEX_NAMES).reshape(-1,1))  # Alternative
print(np.vstack(np.array(p5_INDEX_NAMES)))
print()

p5_list_data = p5_data.split("\n")
p5_list_list_data = [i.split("\t") for i in p5_list_data if i]
p5_np_array = np.array(p5_list_list_data)
p5_np_array = p5_np_array.astype(np.float64)
print("Given Table as Matrix")
print(p5_np_array)
print()

p5_pd_df = pd.DataFrame(p5_np_array, columns=p5_COLUMN_NAMES, index=p5_INDEX_NAMES)
print("Pandas DF")
display(p5_pd_df)

Column names
[0, 5, 10, 15]

Index names
[[ 0]
 [ 5]
 [10]]

Given Table as Matrix
[[0.01 0.06 0.02 0.1 ]
 [0.04 0.13 0.2  0.1 ]
 [0.01 0.15 0.17 0.01]]

Pandas DF


0     5     10    15
0   0.01  0.06  0.02  0.10
5   0.04  0.13  0.20  0.10
10  0.01  0.15  0.17  0.01

### (a) If the score recorded in the grade book is the total number of points earned on the two parts, what is the expected recorded score E(X + Y)? (Enter your answer to one decimal place.)

In [82]:
print("Given Table as Matrix")
print(p5_np_array)
print()

p5a_matrix_of_Y = np.array(p5_COLUMN_NAMES)* np.ones(3).reshape(3,1)
print("Matrix based on the Column names")
print(p5a_matrix_of_Y)
print()

p5a_matrix_of_X = np.array(p5_INDEX_NAMES).reshape(3,1)* np.ones(4)
print("Matrix based on the Row names")
print(p5a_matrix_of_X)
print()

p5a_matrix_of_X_plus_Y = p5a_matrix_of_X + p5a_matrix_of_Y
print("Matrix based on p5a_matrix_of_Y + p5a_matrix_of_X")
print(p5a_matrix_of_X_plus_Y)
print()

p5a_matrix_of_original_array_times_matrix_of_X_plus_Y= p5_np_array * p5a_matrix_of_X_plus_Y
print("(Given Table as Matrix) * (Matrix of X + Y)")
print(p5a_matrix_of_original_array_times_matrix_of_X_plus_Y)
print()

p5a_sum_of_matrix_of_original_array_times_matrix_of_X_plus_Y = np.sum(p5a_matrix_of_original_array_times_matrix_of_X_plus_Y)
print("Sum of the above matrix")
print(p5a_sum_of_matrix_of_original_array_times_matrix_of_X_plus_Y)

Given Table as Matrix
[[0.01 0.06 0.02 0.1 ]
 [0.04 0.13 0.2  0.1 ]
 [0.01 0.15 0.17 0.01]]

Matrix based on the Column names
[[ 0.  5. 10. 15.]
 [ 0.  5. 10. 15.]
 [ 0.  5. 10. 15.]]

Matrix based on the Row names
[[ 0.  0.  0.  0.]
 [ 5.  5.  5.  5.]
 [10. 10. 10. 10.]]

Matrix based on p5a_matrix_of_Y + p5a_matrix_of_X
[[ 0.  5. 10. 15.]
 [ 5. 10. 15. 20.]
 [10. 15. 20. 25.]]

(Given Table as Matrix) * (Matrix of X + Y)
[[0.   0.3  0.2  1.5 ]
 [0.2  1.3  3.   2.  ]
 [0.1  2.25 3.4  0.25]]

Sum of the above matrix
14.5


### (b) If the maximum of the two scores is recorded, what is the expected recorded score? (Enter your answer to two decimal places.)

In [75]:
p5b_matrix_max = np.maximum(p5a_matrix_of_Y, p5a_matrix_of_X)
print("Matrix Max of p5a_matrix_of_Y and p5a_matrix_of_X")
print(p5b_matrix_max)
print()

p5b_matrix_solution = p5_np_array * p5b_matrix_max
print("Matrix of (Given Table as Matrix) * (p5b_matrix_max)")
print(p5b_matrix_solution)
print()

print("Sum of Matrix of (Given Table as Matrix) * (p5b_matrix_max)")
print(np.sum(p5b_matrix_solution))

Matrix Max of p5a_matrix_of_Y and p5a_matrix_of_X
[[ 0.  5. 10. 15.]
 [ 5.  5. 10. 15.]
 [10. 10. 10. 15.]]

Matrix of (Given Table as Matrix) * (p5b_matrix_max)
[[0.   0.3  0.2  1.5 ]
 [0.2  0.65 2.   1.5 ]
 [0.1  1.5  1.7  0.15]]

Sum of Matrix of (Given Table as Matrix) * (p5b_matrix_max)
9.799999999999999


# 6.DEVORESTAT9 5.E.030.
An instructor has given a short quiz consisting of two parts. For a randomly selected student, let X = the number of points earned on the first part and Y = the number of points earned on the second part. Suppose that the joint pmf of X and Y is given in the accompanying table.
<img src="images/5_1_and_5_2_problem_6.png" alt="5_1_and_5_2_problem_6.png" style="float:left;">

In [94]:
p6_data = """
0.03	0.06	0.02	0.10
0.04	0.17	0.20	0.10
0.01	0.15	0.11	0.01


"""
p6_COLUMN_NAMES = [0, 5, 10, 15]
p6_INDEX_NAMES = [0, 5, 10]

print("Column names")
print(p6_COLUMN_NAMES)
print()

print("Index names")
# print(np.array(p6_INDEX_NAMES).reshape(-1,1)) # Alternative
print(np.vstack(np.array(p6_INDEX_NAMES)))
print()

p6_list_data = p6_data.split("\n")
p6_list_list_data = [i.split("\t") for i in p6_list_data if i]
p6_np_array = np.array(p6_list_list_data)
p6_np_array = p6_np_array.astype(np.float64)

print("Given Table as Matrix")
print(p6_np_array)

Column names
[0, 5, 10, 15]

Index names
[[ 0]
 [ 5]
 [10]]

Given Table as Matrix
[[0.03 0.06 0.02 0.1 ]
 [0.04 0.17 0.2  0.1 ]
 [0.01 0.15 0.11 0.01]]


In [86]:
p6_np_array_row = np.sum(p6_np_array, axis=0)
print(p6_np_array_row)
print()

p6_np_array_column = np.sum(p6_np_array, axis=1)
print(p6_np_array_column)

[0.08 0.38 0.33 0.21]

[0.21 0.51 0.28]


In [ ]:
that = np.array([0, 5, 10])

print(p5_np_array_column)
print()

p5_P_of_X_times_X = p5_np_array_column * that
print(p5_P_of_X_times_X)
print()

mean_x = np.sum(p5_P_of_X_times_X)
print(mean_x)
print()


p5_P_of_X_blah = that - mean_x
print(p5_P_of_X_blah)
p5_P_of_X_blah = p5_P_of_X_blah * p5_P_of_X_blah
print(p5_P_of_X_blah)
p5_P_of_X_blah = p5_P_of_X_blah * p5_np_array_column
print(p5_P_of_X_blah)
print()

x_sqrt = np.sum(p5_P_of_X_blah)**(1/2)
print(x_sqrt)

In [ ]:
that_2 = np.array([0, 5, 10, 15])

print(p5_np_array_row)
print()

p5_P_of_Y_times_Y = p5_np_array_row * that_2
print(p5_P_of_Y_times_Y)
print()

mean_y = np.sum(p5_P_of_Y_times_Y)
print(mean_y)
print()


p5_P_of_Y_blah = that_2 - mean_y
print(p5_P_of_Y_blah)
p5_P_of_Y_blah = p5_P_of_Y_blah * p5_P_of_Y_blah
print(p5_P_of_Y_blah)
p5_P_of_Y_blah = p5_P_of_Y_blah * p5_np_array_row
print(p5_P_of_Y_blah)
print()

y_sqrt = np.sum(p5_P_of_Y_blah)**(1/2)
print(y_sqrt)

In [ ]:
print(p5_np_array)
print()

mult_1 = np.array([that, that, that, that])
print(mult_1)
print()

mult_2 = np.array([that_2, that_2, that_2]).transpose()
print(mult_2)
print()

p1 = p5_np_array.transpose()


print(p1)


p1 = p1 * mult_1 * mult_2
print(p1)
print()
p1_sum = np.sum(p1)

print(p1_sum)
print()

p_sol = p1_sum - mean_y * mean_x
print(p_sol)

In [ ]:
part_b = p_sol/(y_sqrt * x_sqrt)

print(part_b)